// Generated by gencpp from file smart_car/FrameToFrame.msg
// DO NOT EDIT!


#ifndef SMART_CAR_MESSAGE_FRAMETOFRAME_H
#define SMART_CAR_MESSAGE_FRAMETOFRAME_H

#include <ros/service_traits.h>


#include <smart_car/FrameToFrameRequest.h>
#include <smart_car/FrameToFrameResponse.h>


namespace smart_car
{

struct FrameToFrame
{

typedef FrameToFrameRequest Request;
typedef FrameToFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FrameToFrame
} // namespace smart_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smart_car::FrameToFrame > {
  static const char* value()
  {
    return "405de59229ff9ecc65cfa6d1fe41484d";
  }

  static const char* value(const ::smart_car::FrameToFrame&) { return value(); }
};

template<>
struct DataType< ::smart_car::FrameToFrame > {
  static const char* value()
  {
    return "smart_car/FrameToFrame";
  }

  static const char* value(const ::smart_car::FrameToFrame&) { return value(); }
};


// service_traits::MD5Sum< ::smart_car::FrameToFrameRequest> should match 
// service_traits::MD5Sum< ::smart_car::FrameToFrame > 
template<>
struct MD5Sum< ::smart_car::FrameToFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smart_car::FrameToFrame >::value();
  }
  static const char* value(const ::smart_car::FrameToFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_car::FrameToFrameRequest> should match 
// service_traits::DataType< ::smart_car::FrameToFrame > 
template<>
struct DataType< ::smart_car::FrameToFrameRequest>
{
  static const char* value()
  {
    return DataType< ::smart_car::FrameToFrame >::value();
  }
  static const char* value(const ::smart_car::FrameToFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smart_car::FrameToFrameResponse> should match 
// service_traits::MD5Sum< ::smart_car::FrameToFrame > 
template<>
struct MD5Sum< ::smart_car::FrameToFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smart_car::FrameToFrame >::value();
  }
  static const char* value(const ::smart_car::FrameToFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_car::FrameToFrameResponse> should match 
// service_traits::DataType< ::smart_car::FrameToFrame > 
template<>
struct DataType< ::smart_car::FrameToFrameResponse>
{
  static const char* value()
  {
    return DataType< ::smart_car::FrameToFrame >::value();
  }
  static const char* value(const ::smart_car::FrameToFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMART_CAR_MESSAGE_FRAMETOFRAME_H
