// Generated by gencpp from file smart_car/FrameToFrameResponse.msg
// DO NOT EDIT!


#ifndef SMART_CAR_MESSAGE_FRAMETOFRAMERESPONSE_H
#define SMART_CAR_MESSAGE_FRAMETOFRAMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace smart_car
{
template <class ContainerAllocator>
struct FrameToFrameResponse_
{
  typedef FrameToFrameResponse_<ContainerAllocator> Type;

  FrameToFrameResponse_()
    : output()  {
    }
  FrameToFrameResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::smart_car::FrameToFrameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_car::FrameToFrameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FrameToFrameResponse_

typedef ::smart_car::FrameToFrameResponse_<std::allocator<void> > FrameToFrameResponse;

typedef boost::shared_ptr< ::smart_car::FrameToFrameResponse > FrameToFrameResponsePtr;
typedef boost::shared_ptr< ::smart_car::FrameToFrameResponse const> FrameToFrameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_car::FrameToFrameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace smart_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'smart_car': ['/home/uav/ROS/car/src/smart_car/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_car::FrameToFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_car::FrameToFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_car::FrameToFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dc0c3656ea8ad48f1d7d90c513fe25a";
  }

  static const char* value(const ::smart_car::FrameToFrameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dc0c3656ea8ad48ULL;
  static const uint64_t static_value2 = 0xf1d7d90c513fe25aULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_car/FrameToFrameResponse";
  }

  static const char* value(const ::smart_car::FrameToFrameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D output\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::smart_car::FrameToFrameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrameToFrameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_car::FrameToFrameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_car::FrameToFrameResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CAR_MESSAGE_FRAMETOFRAMERESPONSE_H
