// Generated by gencpp from file smart_car/KinematicsInverse.msg
// DO NOT EDIT!


#ifndef SMART_CAR_MESSAGE_KINEMATICSINVERSE_H
#define SMART_CAR_MESSAGE_KINEMATICSINVERSE_H

#include <ros/service_traits.h>


#include <smart_car/KinematicsInverseRequest.h>
#include <smart_car/KinematicsInverseResponse.h>


namespace smart_car
{

struct KinematicsInverse
{

typedef KinematicsInverseRequest Request;
typedef KinematicsInverseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KinematicsInverse
} // namespace smart_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smart_car::KinematicsInverse > {
  static const char* value()
  {
    return "cb684d22809e19793d1c5c527b5f8cf4";
  }

  static const char* value(const ::smart_car::KinematicsInverse&) { return value(); }
};

template<>
struct DataType< ::smart_car::KinematicsInverse > {
  static const char* value()
  {
    return "smart_car/KinematicsInverse";
  }

  static const char* value(const ::smart_car::KinematicsInverse&) { return value(); }
};


// service_traits::MD5Sum< ::smart_car::KinematicsInverseRequest> should match 
// service_traits::MD5Sum< ::smart_car::KinematicsInverse > 
template<>
struct MD5Sum< ::smart_car::KinematicsInverseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smart_car::KinematicsInverse >::value();
  }
  static const char* value(const ::smart_car::KinematicsInverseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_car::KinematicsInverseRequest> should match 
// service_traits::DataType< ::smart_car::KinematicsInverse > 
template<>
struct DataType< ::smart_car::KinematicsInverseRequest>
{
  static const char* value()
  {
    return DataType< ::smart_car::KinematicsInverse >::value();
  }
  static const char* value(const ::smart_car::KinematicsInverseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smart_car::KinematicsInverseResponse> should match 
// service_traits::MD5Sum< ::smart_car::KinematicsInverse > 
template<>
struct MD5Sum< ::smart_car::KinematicsInverseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smart_car::KinematicsInverse >::value();
  }
  static const char* value(const ::smart_car::KinematicsInverseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_car::KinematicsInverseResponse> should match 
// service_traits::DataType< ::smart_car::KinematicsInverse > 
template<>
struct DataType< ::smart_car::KinematicsInverseResponse>
{
  static const char* value()
  {
    return DataType< ::smart_car::KinematicsInverse >::value();
  }
  static const char* value(const ::smart_car::KinematicsInverseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMART_CAR_MESSAGE_KINEMATICSINVERSE_H
